#!/usr/bin/env bash

set -eu

output="$1"
status="$2"

printf '%s\n' \
  "IOS_SIM_GATE_UDID=${IOS_SIM_GATE_UDID:-}" \
  "IOS_SIM_GATE_DESTINATION=${IOS_SIM_GATE_DESTINATION:-}" \
  "IOS_SIM_GATE_DERIVED_DATA_PATH=${IOS_SIM_GATE_DERIVED_DATA_PATH:-}" \
  "IOS_SIM_GATE_PROJECT=${IOS_SIM_GATE_PROJECT:-}" \
  "IOS_SIM_GATE_AGENT=${IOS_SIM_GATE_AGENT:-}" \
  "IOS_SIM_GATE_SESSION=${IOS_SIM_GATE_SESSION:-}" \
  "IOS_SIM_GATE_SESSION_IS_SET=${IOS_SIM_GATE_SESSION+x}" >"$output"

exit "$status"
